# Generated by Django 2.0.5 on 2018-06-28 08:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='choice detail'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='content of question'),
        ),
    ]
